/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject1;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
		System.out.print(" Ingrese un número: ");
		int num = new Scanner(System.in).nextInt();
	int factorial = 1;

	for(int i=1;i<=num;i++) 
		factorial *= i; 
	System.out.print(num+"! = "+factorial);
}
	
	
	public void suce() {
		double num;
		System.out.print(" Ingrese un número: ");
	 num = new Scanner(System.in).nextInt();
	 for(int i=1;i<=num;i++) {
	 double resultado = num+2/((num)+1);
	 System.out.print(" Resultado: " +resultado);
	}
		
	}

    }

